In [1]:
import pandas as pd

pd.read_parquet("matched_fashion_dataset_300k_rows.parquet")

,item_id,category,subcategory,sleeve_type,season,fabric,occasion,formality_level,size_range,brand,view_count,click_count,purchase_count,length_cm,price,stocks
0,TNC_000001,tops,formal_shirts,long,all-season,cotton,party,high,XXL,Tommy Hilfiger,91,2,56,69,365256,119
1,TNC_000002,tops,casual_shirts,long,summer,linen,casual,high,L,Adidas,212,125,83,70,249729,104
2,TNC_000003,bottoms,jeans,long,winter,fleece,casual,high,XS,ZARA,166,148,176,95,276724,97
3,TNC_000004,bottoms,jeans,long,summer,denim,casual,low,XXL,Nike,132,410,63,103,314195,123
4,TNC_000005,tops,casual_shirts,long,winter,denim,office,low,L,Nike,506,89,3,77,213034,162
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,TNC_299996,tops,casual_shirts,long,winter,linen,party,high,L,ZARA,2704,154,37,73,331202,169
299996,TNC_299997,bottoms,men_cargos,long,summer,fleece,party,low,XXL,Adidas,190,255,70,109,330060,107
299997,TNC_299998,bottoms,jeans,long,summer,polyester,casual,medium,XXL,Nike,741,7,23,103,351697,101
299998,TNC_299999,tops,printed_hoodies,long,summer,polyester,casual,high,XS,Adidas,453,136,6,79,396990,45
299999,TNC_300000,bottoms,jeans,long,winter,polyester,office,high,XL,Tommy Hilfiger,156,349,46,110,384175,118

In [2]:
pd.read_parquet("matched_fashion_balance_rows_prediction.parquet")

,item_id,date,purchase_count,view_count,price,stocks,sales,stock_value_retail,profit_status,conversion_rate,sales_log,predicted_sales,predicted_profit
0,item_000001,2025-01-31,3.0,3736.0,346555.0,172.0,30383339.0,49100152.0,1.00,60.195342,17.229404,127866.250000,profit
1,item_000001,2025-02-01,3.0,356.0,216545.0,96.0,24742335.0,25600992.0,1.00,70.376131,17.024027,56849.851562,profit
2,item_000001,2025-02-02,0.0,0.0,216545.0,96.0,0.0,25600992.0,1.00,0.000000,0.000000,104502.617188,profit
3,item_000001,2025-02-03,2.0,1044.0,284314.0,49.0,17303367.0,14108619.0,1.00,6.638782,16.666412,32212.800781,profit
4,item_000001,2025-02-04,2.0,1104.0,285865.0,148.0,18683496.0,41282232.0,1.00,6.484313,16.743151,75313.539062,profit
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298145,item_000890,2025-12-27,0.0,0.0,305113.5,183.0,0.0,61526064.0,0.75,0.000000,0.000000,13406.049805,profit
298146,item_000890,2025-12-28,1.0,361.0,347344.0,58.0,6252192.0,20145952.0,1.00,4.986150,15.648443,10358.120117,profit
298147,item_000890,2025-12-29,2.0,1571.0,204049.5,68.0,11992583.0,17865164.0,1.00,7.670717,16.299799,96990.546875,profit
298148,item_000890,2025-12-30,0.0,0.0,204049.5,68.0,0.0,17865164.0,1.00,0.000000,0.000000,165973.046875,profit
298149,item_000890,2025-12-31,0.0,0.0,204049.5,68.0,0.0,17865164.0,1.00,0.000000,0.000000,40149.261719,profit